name: Output information
on: issues

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          cat <<'EOF'
          ${{ toJSON(github.event) }}
          EOF
